build:
  environment:
    timezone: FR
    php:
      version: 7.4

  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

    tests:
      tests:
        override:
          - command: composer run tests-with-coverage
            coverage:
              file: coverage.xml
              format: clover

filter:
  excluded_paths:
    - 'tests/*'
